apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock
  namespace: minecraft-bedrock
spec:
  selector:
    app: minecraft-bedrock
  ports:
    - port: 19132
      protocol: UDP
  # Use LoadBalancer if running on a provider that supports that
  #  type: LoadBalancer
  # or use NodePort on a non-managed system;
  # however, you'll need to lookup port assigned to the service
  type: NodePort
